Fix Client mod not being obfuscated
Minecraft Method names need to be obfuscated else it throws along the lines of: Java NoSuchMethodError minecraft.getMinecraft()